# Generated by Django 3.2 on 2023-01-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_diver_age',
            new_name='default_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_diver_grade',
            new_name='default_street_address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_other_qualifications',
            new_name='default_street_address2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_town_or_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
