# Generated by Django 3.2 on 2023-01-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_name_contact_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ticket_number',
            field=models.CharField(default=1234, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
