# Generated by Django 3.2 on 2023-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_userreview_userreviewform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewform',
            name='review',
            field=models.TextField(max_length=400),
        ),
    ]
